server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lr_database?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mail:
    protocol: smtps
    host: smtp.163.com
    port: 465
    username: 18967220636@163.com
    password: UUvD283xqxYEKyAi
    default-encoding: UTF-8
    from: 18967220636@163.com
    properties:
      mail.smtp.socketFactoryClass: javax.net.ssl.SSLSocketFactory

  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      accessKeyId: ${ALIBABA_ACCESS_KEY_ID}
      accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
      bucketName: answerly
